### ISSUE TITLE
FEATURE

### ISSUE THREAD

**Issue by ghost** [i-net-software/JWebAssembly-API#2]
add jsx like features. Where you can make a string, and then appended that to document.

**Comment by ghost** [comment]
Close this, [i already did this](https://github.com/Eskerepvp/Jekt)

**Comment by Horcrux7** [comment]
Nice! Do you want a reference to your project on the main page of [JWebAssembly-API](https://github.com/i-net-software/JWebAssembly-API)? Or it is more a private project?

**Comment by ghost** [comment]
Its more of a private project.

**Comment by ghost** [comment]
Its more of a private project.
