### ISSUE TITLE
[Inquiry] HTML Source to Element

### ISSUE THREAD

**Issue by Ordiel** [i-net-software/JWebAssembly-API#3]
Is it possible to use plain HTML Text source and create an `de.inetsoftware.jwebassembly.web.dom.Element` (or HTMLElement) from it?

**Comment by Horcrux7** [comment]
I does not understand what you means. Theoretical you can do all what you can do in JavaScript. The web api wrapper are currently spartan. How would this look in JavaScript?

**Comment by Ordiel** [comment]
I am looking at `de.inetsoftware.jwebassembly.web.JSObject#domString`  yet the following comment on it is confusing me

```java
// in wasm code this method should be replaced
``` 

I am wondering if it could be used for something like `JSObject.domString("<div><h1>hello world</h1></div>")` to reduce the verbosity of creating element by element

**Comment by Horcrux7** [comment]
You can do this to receive an JavaScript String. But what you want do with this JavaScript String? Why you does use:

`Windows.document().body().setInnerHTML( "<div><h1>hello world</h1></div>" );
`

In general it is not a good idea to use any JavaScript object in application program code. Also if its sounds like an Java object and it is saved in an variable of type java.lang.Object. It is not an Java object. You can not call any method from it like equals() or hashcode(). You can't it save in HashMap etc.

What you would do in JavaScript with such HTML snipped? The same can you do in Java now.

**Comment by Ordiel** [comment]
I think there was a bit of misunderstanding, this was what I was looking for:

`Windows.document().body().setInnerHTML( "<div><h1>hello world</h1></div>" );`
