### ISSUE TITLE
ask for a all-featured version

### ISSUE THREAD

**Issue by wangdahoo** [i-net-software/JWebAssembly-API#5]
hi, when will be a all-featured version released? is v0.4.0 all-featured?

**Comment by Horcrux7** [comment]
What you means with all featured?

**Comment by Horcrux7** [comment]
Do you are missing a special feature? For example for some DOM API?

Do you can make a PR to improve the speed. Currently I work on bugs in the compiler. The API project has a lower priority. That a PR are welcome.

**Comment by wangdahoo** [comment]
> What you means with all featured?

mean dom api

**Comment by Horcrux7** [comment]
> mean dom api

If the community make pull requests for it.
